### PR TITLE
performance improvements and simplification

### PR DESCRIPTION
**Pull request by amoldavsky**
Hi Sophie,

Thank you very much for sharing this cute little library with the world!

I had a need to use a URL parser for CSS and I went over the source code for curiosity.
First of all, the results in the array had malformed strings like "a,b,c,d", probably something that lodash did. Now fixed!

I noticed that you were using underscore / lodash to help you with getting unique URLs and filtering out unintended URLs. While it looks very nice, code wise, it is bringing up you code complexity to at least O(n^2) but probably closer to O(n^3).

If you look over the source code for _.uniq it is super inefficient and very wasteful because it basically does a loop for your N URLs and than for each it calls _.contain() which is another lookup up to N more elements. Hence, N * N -> O( N^2 ).

In addition I saw that you were doing excludes, using lodash again, after you have already called _.uniq which is another +N iterations because it has to loop through N elements all over again.

I have also commented out the code for removing comments because that is another pass through the entire CSS, and if the CSS is a large String ( like in my case ) that is becoming very significant in terms of time.

All in all, I have completely removed lodash, you do not need it at all !
Code is now O(n), yay! our professors would be proud of us! :)

A great quote I always go by is "less code is better!" :)

Thank you!
-Assaf

### CODE REVIEW

**Comment by s0ph1e** [comment]
Hi @amoldavsky 

Thanks for your contribution.

1. Could you please provide an example of css text which caused issue you described (if it is not a secret)
    >  the results in the array had malformed strings like "a,b,c,d", probably something that lodash did

2. I think removing comments is needed before search because: 
    * I don't want commented out urls in result 
    * They may be tricky and cause a problem if not removed

3. Your suggestion for `dataURIPattern` handles only images, but DataURI has next format: 
    ```
    data:[<mediatype>][;base64],<data>
   ```
  Css file may contain other resource types. I have updated tests for it, please take a look on https://github.com/s0ph1e/node-css-url-parser/blob/master/test/css-parser-test.js#L100-L129

**Comment by amoldavsky** [comment]
When I went to get the CSS file for you that cause the weird links it turned out that one of my input files was an HTML file which got there by my mistake. I am running your library in a loop where I get a bit array of CSS files. So the issue of "a.b.c.d" is a mistake on my end!

Now that you have mentioned what the comment filter is for I agree, it is a good idea, I put it back :)
I have added a test to cover that case.

The comment about the dataUri I also agree, I put it back.

I have updated the pull request, please take a look.

No need for lodash though :)

**Comment by amoldavsky** [comment]
On the same note, one thing that I found to be an issue...

Most ( or even all ) URLs from CSS are relative so you always get results in the form of:
"somedir1/somedir2/file.css"
"/somedie1/somedie2/file.css"

So in my code I had to add a prefixing function which takes a base URL and figures out based on the parsed URL what to prefix the URL with. This can get pretty tricky....

Any reason why you did not want the library to make the request for the CSS file so that this could be handled in one package?

**Comment by s0ph1e** [comment]
> Any reason why you did not want the library to make the request for the CSS file so that this could be handled in one package?

I believe it is out of scope. 
The responsibility of this module is only to parse urls from string. It doesn't care how this string was received. Using http requests will slow down module + it may be tricky as you mentioned. 
BTW I use it in module https://github.com/s0ph1e/node-website-scraper which makes requests (maybe it will be useful)
Anyway feel free to fork this module and create new one which makes requests :)

### About performance

#### V8 optimization
Need to keep in mind that v8 is smart and it makes some optimization inside. If we use custom structure with object we don't allow v8 optimizer to optimize the code. Another performance issue is that this code manipulates large object. It is not recommended.

#### Maintainability of code
Approach with object.keys decreases understandability of the code. For example, if I see 
```javascript
[ 'http://example.com/1.css', 'http://example.com/2.css' ]
```
it is clear for me, but if I see 
```javascript
{
  'http://example.com/1.css': 1, 
  'http://example.com/2.css': 1 
}
```
it is not so clear. Why 1 but not 42 nor 15?

I agree that lodash can be removed. And I found another way to do it - keep arrays, but use `Array.indexOf` to remove duplicates 

#### Measure performance
It was interesting for me, so I wrote some performance tests using `benchmark` module (which was used in jsPerf). You can find them in branch [performance-tests](https://github.com/s0ph1e/node-css-url-parser/tree/performance-tests)
You can run it using
```bash
cd performance-test
npm install
node test.js
```
I used 10 samples with different css files (from 88 chars to 400k chars) and different versions of code: `lodash` - is current one, `object.keys` - is code from this PR, `array.indexof` - is PR #6
Here is my result:
```
node test.js 
text length = 170
lodash x 122,668 ops/sec ±0.77% (93 runs sampled)
object.keys x 351,886 ops/sec ±0.89% (90 runs sampled)
array.indexOf x 723,718 ops/sec ±0.78% (89 runs sampled)
Fastest is array.indexOf
text length = 379034
lodash x 932 ops/sec ±1.08% (90 runs sampled)
object.keys x 889 ops/sec ±1.26% (87 runs sampled)
array.indexOf x 922 ops/sec ±1.03% (91 runs sampled)
Fastest is lodash
text length = 71657
lodash x 5,409 ops/sec ±1.57% (89 runs sampled)
object.keys x 6,123 ops/sec ±1.25% (91 runs sampled)
array.indexOf x 5,798 ops/sec ±0.87% (95 runs sampled)
Fastest is object.keys
text length = 135766
lodash x 4,100 ops/sec ±1.05% (91 runs sampled)
object.keys x 4,211 ops/sec ±0.89% (93 runs sampled)
array.indexOf x 4,315 ops/sec ±0.96% (92 runs sampled)
Fastest is array.indexOf
text length = 12199
lodash x 39,810 ops/sec ±0.98% (90 runs sampled)
object.keys x 49,581 ops/sec ±0.77% (92 runs sampled)
array.indexOf x 54,527 ops/sec ±0.72% (92 runs sampled)
Fastest is array.indexOf
text length = 88
lodash x 130,055 ops/sec ±0.97% (89 runs sampled)
object.keys x 381,234 ops/sec ±1.07% (91 runs sampled)
array.indexOf x 830,764 ops/sec ±1.08% (93 runs sampled)
Fastest is array.indexOf
text length = 2112
lodash x 75,821 ops/sec ±1.14% (89 runs sampled)
object.keys x 112,466 ops/sec ±2.58% (89 runs sampled)
array.indexOf x 173,749 ops/sec ±0.80% (92 runs sampled)
Fastest is array.indexOf
text length = 37681
lodash x 13,822 ops/sec ±1.09% (91 runs sampled)
object.keys x 14,979 ops/sec ±0.68% (89 runs sampled)
array.indexOf x 15,961 ops/sec ±0.84% (95 runs sampled)
Fastest is array.indexOf
text length = 237939
lodash x 1,682 ops/sec ±0.74% (92 runs sampled)
object.keys x 1,694 ops/sec ±0.61% (95 runs sampled)
array.indexOf x 1,634 ops/sec ±0.85% (90 runs sampled)
Fastest is object.keys,lodash
text length = 11821
lodash x 52,608 ops/sec ±1.26% (91 runs sampled)
object.keys x 78,144 ops/sec ±0.50% (95 runs sampled)
array.indexOf x 79,072 ops/sec ±0.67% (92 runs sampled)
Fastest is array.indexOf
```
As you can see, there `object.keys` is faster that `lodash` version, but difference is not so big. And implementation of `array.indexof` is faster that `object.keys` in most cases with minor difference but it keep code more clear. So I decided to go with `array.indexof` (#6 will be merged)

Thank you for your input! :+1:

**Comment by amoldavsky** [comment]
Impressive work :+1: 

I agree about readability, in general, when you need to work with the object long term, in your module, though, since you do not do anything with it really, I would argue it does not matter. It is just a way to create a HashMap instead of array lookups at the end of the day.

I find the test results a bit surprising. What I expected before looking at the numbers was that on larger files Object.keys will win because it is essentially a HashMap, where as Array.indexOf will win on smaller files. The results though are a bit all over he spectrum and I wonder why.... I know that V8 will waste some cycles creating the keys, it creates extra objects behind the scenes, but after that it is a O(1) look up vs O(n) lookup using arrays.

If the case would really be that Object.keys work faster on large files and Array.indexOf on smaller, than a strategy split can be put in place but I don't see these test results as that clear cut. I really want to see why this is.

Lodash is def not a fit here, it is an over kill and a huge beast and I am very surprised that it ran faster than anything at all in these tests :)

Anyway, I really enjoyed this exercise and something has been learned here :+1: 
I added you on LinkedIn :)

Best!
-Assaf

**Comment by amoldavsky** [comment]
Is there a way to chat here other than writing comments? :))

Hey, this really bugged me and I couldn't keep my head off of it so I said ok I will break it down by URL count first... here are my results:

Fastest is array.indexOf
Url count 3

Fastest is object.keys
Url count 86

Fastest is object.keys
Url count 55

Fastest is array.indexOf
Url count 15

Fastest is object.keys
Url count 1

Fastest is array.indexOf
Url count 3

Fastest is array.indexOf
Url count 5

Now this is what I have expected!! The more URLs the better the HashMap performed. Also look at how significant the difference becomes on larger number:

text length = 379034
lodash x 762 ops/sec ±1.10% (81 runs sampled)
object.keys x 925 ops/sec ±0.71% (85 runs sampled)
array.indexOf x 770 ops/sec ±0.78% (81 runs sampled)
Fastest is object.keys
Url count 86
text length = 71657
lodash x 5,241 ops/sec ±0.49% (92 runs sampled)
object.keys x 6,952 ops/sec ±0.90% (94 runs sampled)
array.indexOf x 5,095 ops/sec ±0.76% (87 runs sampled)
Fastest is object.keys
Url count 55

I feel like there is something wrong in the 86 test vs 55 test and I will make another test to isolate purely the indexOf vs Hashing just for my own interest. I will send you a link :)

Best!
-Assaf

**Comment by amoldavsky** [comment]
indexOf wins in all categories :)

Here are the isolated tests, purely for the array manipulations...
https://github.com/amoldavsky/js-array-indexof-vs-hashmap

**Comment by s0ph1e** [comment]
I created chat, feel free to write
[Gitter](https://gitter.im/s0ph1e/node-css-url-parser?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

That's interecting, I'll take a look :+1:

**Pull request closed without merging**
